<a href="https://colab.research.google.com/github/NishmithaJR/Data-Analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
#use tuple to create numpy array
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [ ]:
#Create a 2-D array containing the values 1,2,3,4,5 and 5,6,7,8,9:
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [ ]:
#Create a 1-D array containing the values 1,2,3,4,5:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
#access array element using indexing
arr = np.array([1, 2, 3, 4])
print(arr[1])
print(arr[2] + arr[3])

2
7


In [ ]:
#accessing of 2D-array element
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [ ]:
#Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Slicing arrays

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0, 0:6])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[1 2 3 4 5]
[3 8]
[[2 3 4]
 [7 8 9]]


Data Types in NumPy

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

<U6
int64


In [ ]:
#create a array with data type stirng
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


Converting Data Type on Existing Arrays

In [ ]:
#change data type float into integer
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int64


The Difference Between Copy and View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Get the Shape of an Array

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


Reshaping arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Iterating Arrays

In [ ]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# 3-d array using nditer() method
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
# Sometimes we require corresponding index of the element while iterating, the ndenumerate(
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#initializing numpy array with same number
arr=np.full((2,2),10)
print(arr)

[[10 10]
 [10 10]]


In [ ]:
#initializing numpy array within a range
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr=np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


In [ ]:
# generate random number in array
arr=np.random.randint(1,100,5)
print(arr)

[59 11 98 42 20]


Joining NumPy Arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Using Stack Function

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


numpy intersection and difference

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
np.intersect1d(arr1,arr2)

array([3, 4, 5])

In [ ]:
#return uniq element from arr1
np.setdiff1d(arr1,arr2)

array([1, 2])

In [ ]:
#return uniq element from arr2
np.setdiff1d(arr2,arr1)

array([6, 8])

Addition of numpy array

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2])
print(a)

41


In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2], axis=0)
print(a)

[ 4  6  8 10 13]


In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2], axis=1)
print(a)

[15 26]


numpy array mathematics

In [ ]:
#basic Addition
arr=np.array([10,20,30])
arr=arr+1
print(arr)

[11 21 31]


In [ ]:
#basic subtraction
arr=np.array([10,20,30])
arr=arr-1
print(arr)

[ 9 19 29]


In [ ]:
#basic multiplication
arr=np.array([10,20,30])
arr=arr*2
print(arr)

[20 40 60]


In [ ]:
#basic division
arr=np.array([10,20,30])
arr=arr/2
print(arr)

[ 5. 10. 15.]


In [ ]:
arr=np.array([10,20,30])
np.mean(arr)

20.0

In [ ]:
arr=np.array([10,20,30])
np.median(arr)

20.0

In [ ]:
arr=np.array([10,20,30])
np.std(arr)

8.16496580927726

In [ ]:
np.save('myarray', arr)

In [ ]:
newary=np.load('myarray.npy',)

In [ ]:
print(newary)

[10 20 30]


Splitting NumPy Arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
new_arr=np.array_split(arr,3)
print(new_arr)
print(new_arr[0]) #access array using indexing
print(new_arr[1])
print(new_arr[2])

[array([1, 2]), array([3, 4]), array([5])]
[1 2]
[3 4]
[5]


In [ ]:
#splititng 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
# newarr = np.hsplit(arr, 3)
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Searching Arrays

In [ ]:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4) # return indexes where the value is 4:
print(x)

(array([3, 6]),)


In [ ]:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6]),)


In [ ]:
# Find the indexes where the values are odd:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4]),)


In [ ]:
# Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


Sorting Arrays

In [ ]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


Filtering Arrays

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [ ]:
# Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
# Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
